title: Rodrigo Rocha | Engenheiro de Dados | Machine Learning | Deep Learning
description: Portfólio profissional com projetos de Engenharia de Dados, Machine Learning, AWS, Python e Inteligência Artificial.
baseurl: ""
url: "https://rodrigorocha1234.github.io"

markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag